version: '3.8'

services:
  nest_aws_mongodb:
    container_name: 'nest_aws_mongodb'
    hostname: 'nest_aws_mongodb'
    image: nest_aws_mongodb
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: npm run start:dev && "--log.level=FATAL"
    ports:
      - "${{ secrets.PORT }}:${{ secrets.PORT }}"
    environment:
      - NODE_ENV=production