name: CD Pipeline

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      # Faz o checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v2

      # Configura o Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Limpa o cache e instala os pacotes
      - name: "Clear cache and install packages"
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install

      # Instala os pacotes
      - name: "Install packages"
        run: npm install

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Verifica a versão do Ubuntu para confirmar que o runner está ativo
      - name: Verificar versão do Ubuntu
        run: lsb_release -a

      # Usa a chave SSH para autenticação
      - name: Setup up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Faz o checkout do código
      - name: Check out code
        uses: actions/checkout@v3

      # Testa a conexão SSH
      - name: Testar Conexão SSH
        run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.UBUNTU_USER }}@${{ secrets.UBUNTU_HOST }} "echo 'Conexão SSH bem-sucedida'"

      # Acessa o servidor Ubuntu e executa os comandos
      - name: Access Ubuntu and git pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.UBUNTU_HOST }}
          username: ${{ secrets.UBUNTU_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /srv/sistemas/nest_aws_mongodb-master &&
            git fetch &&
            git checkout master &&
            git pull origin master --rebase &&
            echo "NODE_ENV=${{ secrets.NODE_ENV }}" > .env &&
            echo "TZ=${{ secrets.TZ }}" >> .env &&
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env &&
            echo "MONGO_URI2=${{ secrets.MONGO_URI2 }}" >> .env &&
            echo "PORT=${{ secrets.PORT }}" >> .env &&
            echo "PATH_API=${{ secrets.PATH_API }}" >> .env &&
            echo "SYNCHRONIZE=${{ secrets.SYNCHRONIZE }}" >> .env &&
            echo "RUN_MIGRATIONS=${{ secrets.RUN_MIGRATIONS }}" >> .env &&
            echo "FROM node:22-slim" > Dockerfile &&
            echo "WORKDIR ${{ secrets.PATH_API }}" >> Dockerfile &&
            echo "COPY package*.json ./" >> Dockerfile &&
            echo "RUN apt-get update \ >> Dockerfile &&
            echo "&& apt-get upgrade -y \ >> Dockerfile &&
            echo "&& apt-get install -y --no-install-recommends \ >> Dockerfile &&
            echo "   python3 make g++ \ >> Dockerfile &&
            echo "&& npm install --legacy-peer-deps \ >> Dockerfile &&
            echo "&& apt-get purge -y --auto-remove python3 make g++ \ >> Dockerfile &&
            echo "&& apt-get clean \ >> Dockerfile &&
            echo "&& rm -rf /var/lib/apt/lists/* \ >> Dockerfile &&
            echo "COPY . ." >> Dockerfile &&
            echo "RUN npm run build" >> Dockerfile &&
            echo "EXPOSE ${{ secrets.PORT }}" >> Dockerfile &&
            echo "CMD ["node", "dist/main"]" >> Dockerfile &&
            docker-compose down &&
            docker-compose up -d --build