name: CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  pipeline-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$echo({GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Access Ubuntu and git pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.UBUNTU_HOST }}
          username: ${{ secrets.UBUNTU_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /srv/sistemas/nest_aws_mongodb-master &&
            git fetch &&
            git checkout ${{ steps.extract_branch.outputs.branch }} &&
            git pull origin ${{ steps.extract_branch.outputs.branch }}